Front end features
ConnorScrums/HexTool pull request #30
Opened 2024-10-15 01:54 UTC by jnewman530

Success and failure messages display when file is uploaded that is valid or not. Clear hash button implemented. Styling still needs improvements. Will address next week most likely.

2024-10-15 21:53 UTC, liancent requested changes

2024-10-15 21:53 UTC, liancent commented on templates/index.html
> +            <option value="3">Three</option>
should these be removed?

2024-10-15 22:40 UTC, liancent approved these changes

2024-10-17 21:46 UTC, AnthonyGoncharenko approved these changes
LGTM!

2024-10-17 21:47 UTC, merged